<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-5SIDRBI" failures="1" tests="1" name="Native-Playwright" time="11.209" errors="0" timestamp="2023-01-10T16:08:53 WAT">
  <testcase classname="tests.SoloRunner" name="createNewUserTest" time="7.337">
    <failure type="java.lang.AssertionError" message="L&amp;apos;utilisateur existe déjà">
      <![CDATA[java.lang.AssertionError: L'utilisateur existe déjà
at tests.SoloRunner.createNewUserTest(SoloRunner.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- createNewUserTest -->
  <testcase classname="tests.SoloRunner" name="searchTest" time="0.0">
    <ignored/>
  </testcase> <!-- searchTest -->
  <testcase classname="tests.SoloRunner" name="loginPageNavigationTest" time="0.0">
    <ignored/>
  </testcase> <!-- loginPageNavigationTest -->
  <testcase classname="tests.SoloRunner" name="suppressFromCartTest" time="0.0">
    <ignored/>
  </testcase> <!-- suppressFromCartTest -->
  <testcase classname="tests.SoloRunner" name="LOGOUT" time="0.0">
    <ignored/>
  </testcase> <!-- LOGOUT -->
  <testcase classname="tests.SoloRunner" name="addToCartTest" time="0.0">
    <ignored/>
  </testcase> <!-- addToCartTest -->
</testsuite> <!-- Native-Playwright -->
